# Generated by Django 4.0.3 on 2022-03-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_table',
            name='owner',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
