# Generated by Django 4.0.3 on 2022-03-13 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_url_table_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_table',
            name='creation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='url_table',
            name='exp_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='url_table',
            name='visitor_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
