# Generated by Django 4.0.3 on 2022-03-13 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_url_table_creation_time_url_table_exp_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_table',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='url_table',
            name='visitor_count',
            field=models.IntegerField(default=0),
        ),
    ]
