# Generated by Django 4.0.3 on 2022-03-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='url_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_url', models.CharField(max_length=300)),
                ('short_url', models.CharField(max_length=7)),
            ],
        ),
    ]
