# Generated by Django 4.0.3 on 2022-03-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_url_table_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_table',
            name='visit_day',
            field=models.IntegerField(default=0),
        ),
    ]
