# Generated by Django 4.0.3 on 2022-03-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_url_table_visit_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_table',
            name='visit_day',
            field=models.CharField(default='{"0":0}', max_length=100000),
        ),
    ]
